import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { locales } = useRouter();
  useEffect(() => {}, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {locales.map((locale) => (
        <div key={locale}>
          <Link href={"/test"} {...{ locale }}>
            <a> Go to your {locale}</a>
          </Link>{" "}
          <br />
        </div>
      ))}
    </div>
  );
}
